on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: node:22
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          node-version: 22
      - run: npm install
      - run: npm test
