name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dotenv-cli
        run: npm install -g dotenv-cli

      - name: Install Dependencies
        run: npm install

      - name: Copy .env.test
        run: echo "$ENV_TEST_CONTENT" > .env.test
        env:
          ENV_TEST_CONTENT: ${{ secrets.ENV_TEST }}

      - name: Run Tests
        run: bash scripts/test.sh --detectOpenHandles
